name: dart_unit_test
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  async: ^2.11.0
